### ISSUE TITLE
Is the update stopped?

### ISSUE THREAD

**Issue by abetomo** [a-mitani/mastering-ethereum#18]
@a-mitani 
It was very helpful.
Are not you updating actively now?

**Comment by a-mitani** [comment]
Sorry for late updating.
I recently re-started updating the document. 
In case you find some typos, your opening issues or pull requests are helpful.
Also, adding new topics would be appreciated.

Thank you!

**Comment by abetomo** [comment]
Thank you!
I am looking forward to it.
