### ISSUE TITLE
 「Account Status」「Block Status」項目の表示　　blockStatusComponent　について

### ISSUE THREAD

**Issue by hironohata** [a-mitani/mastering-ethereum#2]
「Account Status」「Block Status」項目の表示
...
まずclient/main.htmlにこれらのコンポーネントのテンプレートを呼び出し表示するためのInclusionsタグ{{> accountStatusComponent}}、{{> accountStatusComponent}}を追加します。

修正
{{> accountStatusComponent}}、{{> blockStatusComponent}}を追加します。

２．
（前略）
  <main class="container-fluid">
    <div class="row-fluid">
      <div class="col-md-8 col-md-offset-2">
        {{> nodeStatusComponent}}
        {{> accountStatusComponent}}
追加
        {{> blockStatusComponent}}
      </div>
。。。

**Comment by a-mitani** [comment]
ご指摘ありがとうございます！
修正しました。
