### ISSUE TITLE
「Node Status」項目をリアクティブな動作にする　　Session　undefined

### ISSUE THREAD

**Issue by hironohata** [a-mitani/mastering-ethereum#3]
「「Node Status」項目をリアクティブな動作にする」　で　Session.＊がerrorとなり、node、account、blockのStatusが表示されません。

以下を追加すると稼働するようになります。
$ meteor add session 

なお、環境はOSXです。

**Comment by a-mitani** [comment]
ご指摘ありがとうございます！！
Meteorのバージョンが新しいとデフォルトでSessionパッケージがインストールされないようですね。
Tipsとして追記しました。
