### ISSUE TITLE
コントリビューションの手順について

### ISSUE THREAD

**Issue by shogochiai** [a-mitani/mastering-ethereum#37]
https://github.com/ethereumbook/ethereumbook を翻訳していると理解しているのですが、Issueにて着手範囲を宣言すれば翻訳に貢献できるのでしょうか？

**Comment by shogochiai** [comment]
私が関心のある書籍とリポジトリ名が同じで、内容が異なるのかもしれません。誤解していたらすみません。

https://book.ethereum-jp.net/
https://github.com/ethereumbook/ethereumbook

**Comment by a-mitani** [comment]
気づくのが遅れて返信が遅れました。申し訳ないです。

お書きいただいたように、本プロジェクトは [Antonopoulosの書籍](https://github.com/ethereumbook/ethereumbook)の翻訳プロジェクトとは内容が異なる独自の書籍のプロジェクトになります。

 [Antonopoulosの書籍](https://github.com/ethereumbook/ethereumbook)は Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International Licenseであり、翻訳版の公開はライセンス違反になっていますので・・・(^^;

**Comment by shogochiai** [comment]
お返事ありがとうございます。背景承知いたしました。

翻訳可能性につきましては詳しくは書きにくいのですが、現在オライリージャパン様を主体に親会社である米国オライリーメディア様に近い方法で翻訳/出版可能にならないか相談を行う運びになっております。とりいそぎご報告までに。
