### ISSUE TITLE
脚注に飛ばない

### ISSUE THREAD

**Issue by tmsanrinsha** [a-mitani/mastering-ethereum#4]
例えば[ブロックチェーン革命 | Ethereum入門](http://book.ethereum-jp.net/what_is_ethereum/blockchainrev_md.html)にあるUTXOにある脚注へのリンクですが
http://book.ethereum-jp.net/what_is_ethereum/blockchainrev_md.html#fn_1
になっており、一方脚注部分のHTMLは

``` html
<a href="#fn_1" id="reffn_1">1</a>
```

となっており、飛びません。URLを
http://book.ethereum-jp.net/what_is_ethereum/blockchainrev_md.html#reffn_1
にするか、idの方を合わせる必要があります。

ソース https://github.com/a-mitani/mastering-ethereum/blob/master/what_is_ethereum/blockchainrev_md.md
を見ると

> [^1] Aから 10 BTC 送金を受けたトランザクションと、Bから 20 BTC 送金を受けたトランザクションの２つ。

になっていますが、正しくは

> [^1]: Aから 10 BTC 送金を受けたトランザクションと、Bから 20 BTC 送金を受けたトランザクションの２つ。

だったりしないでしょうか？

**Comment by a-mitani** [comment]
遅ればせながら、ご指摘ありがとうございます！
おっしゃるとおりでした。脚注の被リンク側にコロンが必要だったのですね・・・
該当箇所、修正いたしました。

また何かあればよろしくおねがいします！ m(. .)m

**Comment by tmsanrinsha** [comment]
ご対応有難うございます！
