### ISSUE TITLE
Gethをプライベート・ネットで起動する におけるオプションの変更

### ISSUE THREAD

**Issue by him0** [a-mitani/mastering-ethereum#6]
現在のバーション

```
VERSION:
   1.4.10-stable-5f55d95a
```

では、[Gethをプライベート・ネットで起動する](http://book.ethereum-jp.net/first_use/connect_to_private_net.html)で記載されているコマンドでは、Gethを起動することができません。

エラーログとして `~/eth_private_net/geth_err.log` に

```
flag provided but not defined: -genesis
```

が出力されました。

```
$ geth init ~/eth_private_net/myGenesis.json
$ geth --networkid "10" --nodiscover --datadir "~/eth_private_net" console 2>> ~/eth_private_net/geth_err.log
```

で起動できました。

参考
[Ethereum(geth)でプライベート・ネットワークを作る手順 - Qiita](http://qiita.com/hshimo/items/8b69975d40466022f278)

**Comment by a-mitani** [comment]
him0さん、こんにちは。

ご指摘ありがとうございます！
version 1.4.3 あたりで「--genesis」フラグが排除されたみたいですね (^^;）

initでの方法に修正しました。
